import React from "react";
import Head from "next/head";
function About() {
  const about = (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      This is about page
    </div>
  );
  return about;
}

export default About;
