import React from "react"
import Head from "next/head"

function Contact() {
  const contact = (
    <div>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      This is contact page You can contact me on my email diptabose484@gmail.com
      or Whatsapp me on +91 9381327381
    </div>
  );
  return contact;
}

export default Contact;
