import { useEffect , useState } from "react"; 
import Head from "next/head";
import styles from "../styles/Home.module.css";
import BlogCard from "../components/BlogCard";
import AppBar from "@mui/material/AppBar";
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab'
import IconButton from "@mui/material/IconButton";
import MenuIcon from '@mui/icons-material/Menu';
import Box from "@mui/material/Box";
import Button from "@mui/material/Button"


export default function Home() {
  const[index , setIndex]=useState(0);
  
  const handleIndex=(e , newIndex)=>{
    setIndex(newIndex);
  }

  return (
    <div>
      <Head>
        <title>Blogger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar elevation={0} position="sticky" >
         <IconButton >
           <MenuIcon />
         </IconButton>
         
      </AppBar>
      <Box sx={{backgroundColor:"primary"}}>
      <Tabs value={index}  variant="fullWidth" onChange={handleIndex}>
           <Tab label="Home" />
           <Tab label="Contacts" />
           <Tab label="About" />
      </Tabs>
      </Box> 
      
      <main className="w-full px-2">
        <section>
          <div id="blog_heading_category">
            <div id="popular_blogs" className="mt-4">
              <h2 className="text-3xl">Popular blogs</h2>
              <Box><Button variant="contained" >Lets test this</Button></Box>
              
              <div
                id="popular_blogs_container"
                className="flex flex-col items-center"
              >
                <BlogCard title="Ala vaikunthapuram lo" content="sare"/>
                <BlogCard title="Ala vaikunthapuram lo" content="sare"/>
                <BlogCard title="Ala vaikunthapuram lo" content="sare"/>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
